export const POST_SET = 'POST_SET';
export const POSTS_SET = 'POSTS_SET';
export const POST_LIKE = 'POST_LIKE';
export const POST_UNLIKE = 'POST_UNLIKE';
export const POST_DELETE = 'POST_DELETE';
export const POST_STATE_CLEAR = "POST_STATE_CLEAR";

export const COMMENT_SET = 'COMMENT_SET';
export const COMMENTS_SET = 'COMMENTS_SET';
export const COMMENT_DELETE = 'COMMENT_DELETE';
export const COMMENT_STATE_CLEAR = "COMMENT_STATE_CLEAR";

export const MESSAGE_SET = 'MESSAGE_SET';
export const MESSAGES_SET = 'MESSAGES_SET';
export const MESSAGE_DELETE = 'MESSAGE_DELETE';
export const MESSAGE_STATE_CLEAR = "MESSAGE_STATE_CLEAR";

export const NOTIFICATION_SET = 'NOTIFICATION_SET';
export const NOTIFICATIONS_SET = 'NOTIFICATIONS_SET';
export const NOTIFICATION_UPDATE = 'NOTIFICATION_UPDATE';
export const NOTIFICATION_STATE_CLEAR = "NOTIFICATION_STATE_CLEAR";



export const USER_SET = 'USER_SET';
export const USERS_SET = 'USERS_SET';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_DELETE = 'USER_DELETE';
export const USER_STATE_CLEAR = "USER_STATE_CLEAR";


export const COMMON_ERROR_SET = 'COMMON_ERROR_SET';
export const COMMON_MESSAGE_SET = 'COMMON_MESSAGE_SET';
export const COMMON_LOADING_SET = 'COMMON_LOADING_SET';